version: "3.8"

services: 
    web:
        build: 
            context: . 
        ports:
            - "8000:8000"
        volumes: 
            - ./app:/usr/src/app
        command: "python manage.py runserver 0.0.0.0:8000"
        env_file: .env
        depends_on: 
            - db
            - redis
    
    db:
        image: postgres:alpine
        env_file: .env
        volumes: 
            - pg_data:/var/lib/postgresql/data
    redis:
        image: redis:alpine

volumes: 
    pg_data:

